### PR TITLE
fix: make pluginOptions work as documented

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by jedmao** [comment]
I'm not understanding what this is fixing. Can you elaborate?

**Comment by Guria** [comment]
Current documentation states following way to define options:
```
module.exports = {
  plugins: [
    {
      plugin: CracoLinariaPlugin,
      options: {
        // Linaria options
      },
    },
  ],
}
```
But this doesn't works since current version tries to get `config` property of pluginOptions. Which is obviously `undefined` in this case.

**Comment by jedmao** [comment]
OK sorry, but I'm really struggling to understand the root issue here. Are you suggesting that `(undefined || undefined || {}).config || {}` doesn't work in that it throws an error or something? What is the scenario in which this breaks? What is the expected result here and how does moving the `(` help? I'm not seeing how.

**Comment by Guria** [comment]
```
({ someLinariaOption: true } || undefined || {}).config || {} // {}
```
```
{ someLinariaOption: true } || (undefined || {}).config || {} // {} // { someLinariaOption: true }
```

**Pull request merged**
